Repository necodeIT/lb_planner, pull requests merged in 2023-11, with the labels that each got.

#27 roadmap/milestones subpage
  CONSTANTS.php
  js/roadmap.js
  locale/de.csv
  locale/en.csv
  locale/keys.csv
  resources/check.svg
  resources/pfp_kocagoel.jpg
  resources/pfp_mceachnie.jpg
  resources/pfp_polat.jpg
  resources/pfp_riedler.jpg
  roadmap/index.php
  snippets/navbar.php
  style/main.less
  style/roadmap.less
Labels: enhancement

#46 oops
  roadmap/index.php
Labels: bug

#47 Lp 175 fix shit n stuff
  js/roadmap.js
  roadmap/index.php
  style/roadmap.less
Labels: bug, enhancement

#53 parse return struct defs
  document_services.py
Labels: enhancement
